#z1 = KITCHEN_2

esphome:
  name: geothermie
  friendly_name: Geothermie

esp8266:
  board: nodemcuv2

# Enable logging
logger:

captive_portal:

packages:
  globals: github://jlacasse/openZoningPannel/packages/globals.yml
  configurations: github://jlacasse/openZoningPannel/packages/configurations.yml
  binary_sensors: github://jlacasse/openZoningPannel/packages/binary_sensors.yml
  switches: github://jlacasse/openZoningPannel/packages/switches.yml
  select: github://jlacasse/openZoningPannel/packages/select.yml
  automation: github://jlacasse/openZoningPannel/packages/automation.yml
